// Generated by ts-to-zod
import { z } from "zod";

export const loginRequestSchema = z.object({
    email: z.string(),
    password: z.string(),
});

export const oTPRequestSchema = z.object({
    slug: z.string(),
});

export const oTPRegisterRequestSchema = z.object({
    name: z.string(),
    slug: z.string(),
    identifier: z.string(),
    secret: z.string(),
});

export const createAccountRequestSchema = z.object({
    email: z.string(),
    password: z.string(),
    name: z.string(),
    username: z.string(),
    organization_id: z.string().optional(),
});

export const createOrganizationRequestSchema = z.object({
    name: z.string(),
});
